const down = require('../assets/icons/down.png')
const home = require('../assets/icons/home.png')
const heart = require('../assets/icons/heart.png')
const heartfilled = require('../assets/icons/heartfilled.png')
const catalogue = require('../assets/icons/catalogue.png')
const cart = require('../assets/icons/cart.png')
const userfilled = require('../assets/icons/userfilled.png')
const user = require('../assets/icons/user.png')
const bell = require('../assets/icons/bell.png')
const menu = require('../assets/icons/menu.png')
const like = require('../assets/icons/like.png')
const search = require('../assets/icons/search.png')
const more = require('../assets/icons/more.png')
const back = require('../assets/icons/back.png')
const thumb = require('../assets/icons/thumb.png')
const minus = require('../assets/icons/minus.png')
const plus = require('../assets/icons/plus.png')

export default{down, home, heart, heartfilled, catalogue, cart, user, userfilled, bell, menu, like, more, search, back, thumb, minus, plus}